Add DBCTL latest build

diff --git a/cli/db/app/mysql/migrate b/cli/db/app/mysql/migrate
--- a/cli/db/app/mysql/migrate
+++ b/cli/db/app/mysql/migrate
@@ -58,64 +58,72 @@ function db-migrate-execute {
 
   export IDENTIFIER=${DB_DEPLOYMENT_TYPE}.mysql.${ORGANIZATION}.${TEAM}.${PRODUCT}.${DB_NAME}.${ENVIRONMENT}
   export DB_DIRECTORY=$CURRENT_DIRECTORY/.run.db/${IDENTIFIER}
-  
+
+  mkdir -p ${DB_DIRECTORY}
+  export DB_MIGRATIONS_DIRECTORY=$DB_DIRECTORY/migrations
+  mkdir -p $DB_MIGRATIONS_DIRECTORY/$DB_SCHEMA
+  rm -rf $DB_MIGRATIONS_DIRECTORY/$DB_SCHEMA/*
+  cp -r $BLUEPRINT_MIGRATIONS_DIRECTORY/* $DB_MIGRATIONS_DIRECTORY/$DB_SCHEMA/
+  ./dbctl mysql role get-credential $DB_NAME $ENVIRONMENT $DB_MIGRATION_ROLE_NAME
+  $(./dbctl mysql role use-credential $DB_NAME $ENVIRONMENT $DB_MIGRATION_ROLE_NAME)
+
+  DB_MIGRATION_USERNAME="${DB_NAME}_migrations"
+  DB_MIGRATION_PASSWORD=$DBCTL_PASSWORD
+
   DB_HOST=""
   if [[ "$DB_DEPLOYMENT_TYPE" == "hosted" ]]; then
     DB_HOST=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_host")
+    DB_PORT=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_port")
+    if [[ "$DB_PORT" == "null" ]]; then
+      echo -e "${GREEN}[DBCTL]${NC} Using default ${YELLOW}DB_PORT=3306${NC}"
+      DB_PORT=3306
+    fi
+    DB_HOST="$DB_HOST:$DB_PORT"
   elif [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
-    SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
-    DB_DEPLOYMENT_GENERATED_FILE="${ENVIRONMENT}-deployed.yml"
-    if [[ ! -f $DB_DIRECTORY/$DB_DEPLOYMENT_GENERATED_FILE ]]; then
-      echo -e "${RED}ERROR:${NC} No generated ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please run ${YELLOW}./dbctl mysql deploy $DB_NAME $ENVIRONMENT${NC} first."
-      exit 1;
-    else
-      if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
-        DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_port')
-        DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_host')
-        DB_HOST="127.0.0.1:$DB_SSH_TUNNEL_PORT"
+    # Get DB_TARGET_HOST and DB_TARGET_PORT
+
+    # If we are using DB-DEPLOY-IMPORTED
+    DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.host')
+    DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.port')
+
+    if [[ "$DB_TARGET_HOST" == "null" ]]; then
+      DB_DEPLOYMENT_GENERATED_FILE="${ENVIRONMENT}-deployed.yml"
+      if [[ ! -f $DB_DIRECTORY/$DB_DEPLOYMENT_GENERATED_FILE ]]; then
+        echo -e "${RED}ERROR:${NC} No generated ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+        exit 1;
+      else
         DB_TARGET_HOST=$($yq r $DB_DIRECTORY/$DB_DEPLOYMENT_GENERATED_FILE "db.$DB_DEPLOYMENT_TYPE.deployed.db.host")
         DB_TARGET_PORT=$($yq r $DB_DIRECTORY/$DB_DEPLOYMENT_GENERATED_FILE "db.$DB_DEPLOYMENT_TYPE.deployed.db.port")
         if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
-          echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl mysql deploy $DB_NAME $ENVIRONMENT${NC} first."
-          exit 1;
-        fi
-      else
-        DB_HOST=$($yq r $DB_DIRECTORY/$DB_DEPLOYMENT_GENERATED_FILE "db.$DB_DEPLOYMENT_TYPE.deployed.db.host")
-        DB_PORT=$($yq r $DB_DIRECTORY/$DB_DEPLOYMENT_GENERATED_FILE "db.$DB_DEPLOYMENT_TYPE.deployed.db.port")
-        if [[ "$DB_HOST" == "" ]] || [[ "$DB_HOST" == "null" ]] || [[ "$DB_PORT" == "" ]] || [[ "$DB_PORT" == "null" ]]; then
-          echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl mysql deploy $DB_NAME $ENVIRONMENT${NC} first."
+          echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
           exit 1;
         fi
       fi
+    else
+      DB_PROVIDER_USER_PREFIX=$($yq r $BLUEPRINT_DATABASE_FILE db.apsara.db_provider_root_credential.username)
+      DB_MIGRATION_USERNAME="${DB_PROVIDER_USER_PREFIX}_migrations"
+    fi
+
+    if [[ "$DB_TARGET_PORT" == "null" ]]; then
+      echo -e "${GREEN}[DBCTL]${NC} Using default ${YELLOW}DB_TARGET_PORT=3306${NC}"
+      DB_TARGET_PORT=3306
+    fi
+
+    SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
+    if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
+      DB_SSH_TUNNEL_IDENTIFIER="$DB_NAME.$ENVIRONMENT"
+      DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_port')
+      DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_host')
+      ./dbctl util ssh-tunnel $DB_SSH_TUNNEL_IDENTIFIER $DB_SSH_TUNNEL_HOST $DB_SSH_TUNNEL_PORT $DB_TARGET_HOST $DB_TARGET_PORT
+      DB_HOST="localhost:$DB_SSH_TUNNEL_PORT"
+    else
+      DB_HOST="$DB_TARGET_HOST:$DB_TARGET_PORT"
     fi
   fi
 
   if [[ -z "$DB_HOST" ]] || [[ "$DB_HOST" == "null" ]] || [[ "$DB_HOST" == "" ]]; then
     echo -e "${RED}ERROR:${NC} No DB_HOST is retrieved for migrations. Script will abort."
     exit 1;
-  fi
-
-  mkdir -p ${DB_DIRECTORY}
-  export DB_MIGRATIONS_DIRECTORY=$DB_DIRECTORY/migrations
-  mkdir -p $DB_MIGRATIONS_DIRECTORY/$DB_SCHEMA
-  cp -r $BLUEPRINT_MIGRATIONS_DIRECTORY/* $DB_MIGRATIONS_DIRECTORY/$DB_SCHEMA/
-  ./dbctl mysql role get-credential $DB_NAME $ENVIRONMENT $DB_MIGRATION_ROLE_NAME
-  $(./dbctl mysql role use-credential $DB_NAME $ENVIRONMENT $DB_MIGRATION_ROLE_NAME)
-
-  local DB_PROVIDER_INSTANCE_ID=""
-  local DB_PROVIDER_INSTANCE_HOST=""
-
-  # Currently instance mode only enabled in Apsara
-  if [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
-    DB_PROVIDER_INSTANCE_ID=$($yq r $BLUEPRINT_DATABASE_FILE db.apsara.db_provider_instance.id)
-    DB_PROVIDER_INSTANCE_HOST=$($yq r $BLUEPRINT_DATABASE_FILE db.apsara.db_provider_instance.host)
-  fi
-
-  DB_MIGRATION_USERNAME="${DB_NAME}_migrations"
-  DB_MIGRATION_PASSWORD=$DBCTL_PASSWORD
-  if [[ "$DB_PROVIDER_INSTANCE_ID" != "" ]] && [[ "$DB_PROVIDER_INSTANCE_ID" != "null" ]] && [[ "$DB_PROVIDER_INSTANCE_HOST" != "" ]] && [[ "$DB_PROVIDER_INSTANCE_HOST" != "null" ]]; then
-    DB_PROVIDER_USER_PREFIX=$($yq r $BLUEPRINT_DATABASE_FILE db.apsara.db_provider_root_credential.username)
-    DB_MIGRATION_USERNAME="${DB_PROVIDER_USER_PREFIX}_migrations"
   fi
 
   ansible-playbook db/playbooks/dbctl-db-migrate.yml \
@@ -130,39 +138,11 @@ function db-migrate-execute {
     -e "db_migration_username=${DB_MIGRATION_USERNAME}" \
     -e "db_migration_password=${DB_MIGRATION_PASSWORD}" > /dev/null
 
-  if [[ "${DB_DEPLOYMENT_TYPE}" == "apsara" ]]; then
-    SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
-    if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
-      echo -e "${GREEN}[DBCTL]${NC} Will migrate Apsara DB Database via SSH tunnel"
-      DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_port')
-      DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_host')
-      echo -e "${GREEN}[DBCTL]${NC} ${YELLOW}[TUNNEL]${NC} --> ssh -M -S apsara-tunnel-migrate-${DB_SSH_TUNNEL_PORT} -fnNT -L ${DB_SSH_TUNNEL_PORT}:${DB_HOST}:${DB_PORT} ${DB_SSH_TUNNEL_HOST}"
-      echo -e "${GREEN}[DBCTL]${NC} ${YELLOW}[TUNNEL-EXIT(For Troubleshooting)]${NC} --> ssh -S apsara-tunnel-migrate-${DB_SSH_TUNNEL_PORT} -O exit ${DB_SSH_TUNNEL_HOST}"
-
-      ./dbctl tunnel create ${DB_NAME} mysql ${ENVIRONMENT}
-      pushd $DB_MIGRATIONS_DIRECTORY
-        echo '' > settings.gradle
-        gradle -i flywayBaseline
-        gradle -i flywayMigrate
-      popd
-      ./dbctl tunnel destroy ${DB_NAME} mysql ${ENVIRONMENT}
-
-    else
-      echo -e "${GREEN}[DBCTL]${NC} Will migrate Apsara DB Database"
-      pushd $DB_MIGRATIONS_DIRECTORY
-        echo '' > settings.gradle
-        gradle -i flywayBaseline
-        gradle -i flywayMigrate
-      popd
-    fi
-  elif [[ "${DB_DEPLOYMENT_TYPE}" == "hosted" ]]; then
-    echo -e "${GREEN}[DBCTL]${NC} Will migrate MySQL Database"
-    pushd $DB_MIGRATIONS_DIRECTORY  
-      echo '' > settings.gradle
-      gradle -i flywayBaseline
-      gradle -i flywayMigrate
-    popd
-  fi
+  pushd $DB_MIGRATIONS_DIRECTORY
+    echo '' > settings.gradle
+    gradle -i flywayBaseline
+    gradle -i flywayMigrate
+  popd
 }
 
 if [ $# == 0 ]; then
diff --git a/cli/db/app/mysql/mysql-client b/cli/db/app/mysql/mysql-client
--- a/cli/db/app/mysql/mysql-client
+++ b/cli/db/app/mysql/mysql-client
@@ -49,36 +49,63 @@ function db-mysql-client-execute {
   local DB_NAME=$1
   local ENVIRONMENT=$2
   local ROLE_NAME=$3
-  
+
   local BLUEPRINT_DIRECTORY=$(pwd)/db/blueprint
   local BLUEPRINT_DATABASE_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/${ENVIRONMENT}.yml
   local BLUEPRINT_ROLES_DIRECTORY=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}
   local BLUEPRINT_ROLES_CREATION_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/creation.sql
-  
-  DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
-  DB_HOST=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_host")
+
   export IDENTIFIER=${DB_DEPLOYMENT_TYPE}.mysql.${ORGANIZATION}.${TEAM}.${PRODUCT}.${DB_NAME}.${ENVIRONMENT}
   export DB_DIRECTORY=$CURRENT_DIRECTORY/.run.db/${IDENTIFIER}
   mkdir -p ${DB_DIRECTORY}
   ./dbctl mysql role get-credential $DB_NAME $ENVIRONMENT $ROLE_NAME
   $(./dbctl mysql role use-credential $DB_NAME $ENVIRONMENT $ROLE_NAME)
+  echo -e "${YELLOW}==========================================================================================${NC}"
+  echo -e "${GREEN}[DBCTL]${NC} PSQL Client for - ${YELLOW}${DB_HOST}/${DB_NAME}/${ROLE_NAME}${NC} - "
+  echo -e "${YELLOW}==========================================================================================${NC}"
 
-  local SSH_ENABLED=$($yq r $BLUEPRINT_DATABASE_FILE "db.${DB_DEPLOYMENT_TYPE}.db_provider_option.ssh_tunnel.enabled")
-  if [[ ${SSH_ENABLED} == "true" ]]; then
-    local SSH_PORT=$($yq r $BLUEPRINT_DATABASE_FILE "db.${DB_DEPLOYMENT_TYPE}.db_provider_option.ssh_tunnel.tunnel_port")
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    echo -e "${GREEN}[DBCTL]${NC} MYSQL Client for - ${YELLOW}127.0.0.1:${SSH_PORT}/${DB_NAME}/${ROLE_NAME}${NC} - "
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    ./dbctl tunnel create ${DB_NAME} mysql ${ENVIRONMENT}
-    mysql -u $DBCTL_USERNAME -D $DB_NAME -h 127.0.0.1 -p"$DBCTL_PASSWORD" --port=${SSH_PORT}
-    ./dbctl tunnel destroy ${DB_NAME} mysql ${ENVIRONMENT}
-  else
-    # TODO
-    # this currently only works on hosted as DB_HOST value will be null if it's not hosted
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    echo -e "${GREEN}[DBCTL]${NC} MYSQL Client for - ${YELLOW}${DB_HOST}/${DB_NAME}/${ROLE_NAME}${NC} - "
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    mysql -u $DBCTL_USERNAME -D $DB_NAME -h ${DB_HOST} -p"$DBCTL_PASSWORD"
+  DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
+
+  if [[ "$DB_DEPLOYMENT_TYPE" == "hosted" ]]; then
+    DB_HOST=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_host")
+    DB_PORT=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_port")
+    if [[ "$DB_PORT" == "null" ]]; then
+      DB_PORT=3306
+    fi
+    mysql -u ${DBCTL_USERNAME} -h ${DB_HOST} --password=${DBCTL_PASSWORD} --port ${DB_PORT} --protocol tcp ${DB_NAME}
+  elif [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
+    SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
+
+    if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
+      DB_SSH_TUNNEL_IDENTIFIER="$DB_NAME.$ENVIRONMENT"
+      DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_port')
+      DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_host')
+      DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.host')
+      DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.port')
+      if [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+          DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.host')
+          DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.port')
+          if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+            echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+            exit 1;
+          fi
+      fi
+      ./dbctl util ssh-tunnel $DB_SSH_TUNNEL_IDENTIFIER $DB_SSH_TUNNEL_HOST $DB_SSH_TUNNEL_PORT $DB_TARGET_HOST $DB_TARGET_PORT
+
+      mysql -u ${DBCTL_USERNAME} -h 127.0.0.1 --password=${DBCTL_PASSWORD} --port=${DB_SSH_TUNNEL_PORT} ${DB_NAME}
+    else
+      DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.host')
+      DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.port')
+      if [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+          DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.host')
+          DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.port')
+          if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+            echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+            exit 1;
+          fi
+      fi
+      mysql -u ${DBCTL_USERNAME} -h ${DB_TARGET_HOST} --password=${DBCTL_PASSWORD} --port=${DB_TARGET_PORT} ${DB_NAME}
+    fi
   fi
 }
 
diff --git a/cli/db/app/mysql/role/configure b/cli/db/app/mysql/role/configure
--- a/cli/db/app/mysql/role/configure
+++ b/cli/db/app/mysql/role/configure
@@ -29,6 +29,7 @@ function db-mysql-role-configure-validate {
   local BLUEPRINT_DATABASE_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/${ENVIRONMENT}.yml
   local BLUEPRINT_ROLES_DIRECTORY=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}
   local BLUEPRINT_ROLES_CREATION_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/creation.sql
+  local BLUEPRINT_ROLES_REVOCATION_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/revocation.sql
 
   if [[ ! -f "${BLUEPRINT_DATABASE_FILE}" ]]; then
     echo -e "${RED}ERROR:${NC} No database specification file found for ${YELLOW}${DB_NAME}/${ENVIRONMENT}.yml${NC}. [${YELLOW}${BLUEPRINT_DATABASE_FILE}${NC}]"
@@ -44,6 +45,11 @@ function db-mysql-role-configure-validate {
     echo -e "${RED}ERROR:${NC} No ROLES creation.sql file found for ${YELLOW}${DB_NAME}/${ENVIRONMENT}/${ROLE_NAME}${NC}. [${YELLOW}${BLUEPRINT_ROLES_CREATION_FILE}${NC}]"
     exit 1
   fi
+
+  if [[ ! -f "${BLUEPRINT_ROLES_REVOCATION_FILE}" ]]; then
+    echo -e "${RED}ERROR:${NC} No ROLES revocation.sql file found for ${YELLOW}${DB_NAME}/${ENVIRONMENT}/${ROLE_NAME}${NC}. [${YELLOW}${BLUEPRINT_ROLES_REVOCATION_FILE}${NC}]"
+    exit 1
+  fi
 }
 
 function db-mysql-role-configure-execute {
@@ -55,6 +61,7 @@ function db-mysql-role-configure-execute {
   local BLUEPRINT_DATABASE_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/${ENVIRONMENT}.yml
   local BLUEPRINT_ROLES_DIRECTORY=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}
   local BLUEPRINT_ROLES_CREATION_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/creation.sql
+  local BLUEPRINT_ROLES_REVOCATION_FILE=${BLUEPRINT_DIRECTORY}/mysql/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/revocation.sql
 
   DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
   export IDENTIFIER=${DB_DEPLOYMENT_TYPE}.mysql.${ORGANIZATION}.${TEAM}.${PRODUCT}.${DB_NAME}.${ENVIRONMENT}
@@ -105,6 +112,7 @@ function db-mysql-role-configure-execute {
       -e "db_directory=${DB_DIRECTORY}" \
       -e "db_role_name=${ROLE_NAME}" \
       -e "db_role_creation_file=${BLUEPRINT_ROLES_CREATION_FILE}" \
+      -e "db_role_revocation_file=${BLUEPRINT_ROLES_REVOCATION_FILE}" \
       -e "organization=${ORGANIZATION}" \
       -e "team=${TEAM}" \
       -e "product=${PRODUCT}" \
diff --git a/cli/db/app/postgres/deploy b/cli/db/app/postgres/deploy
--- a/cli/db/app/postgres/deploy
+++ b/cli/db/app/postgres/deploy
@@ -2,9 +2,6 @@
 set -e
 trap "exit" INT
 
-source ./db/app/meta
-source ./db/app/namespace
-
 yq=./.bin.db/yq
 jq=./.bin.db/jq
 CURRENT_DIRECTORY=$(pwd)
@@ -81,6 +78,24 @@ function execute-db-deploy-apsara-confirmation {
     fi
 }
 
+function execute-db-deploy-gcp-confirmation {
+    DB_DIRECTORY=$1
+    rm -f $DB_DIRECTORY/gcp_db.json
+    rm -f $DB_DIRECTORY/TFAPPLYOUTPUT
+    rm -f $DB_DIRECTORY/VAULTUPLOADOUTPUT
+    
+    echo -e "${YELLOW} NOTE: After the procedure We will need to synchronize the DB Credential to Secrets Management - Vault.${NC}"
+    echo -e "${YELLOW} Are you sure you have configured the GITHUB_USERNAME & CERTIFICATE correctly and have verified that you have the required permission to do this?${NC}"
+    echo -e "${RED}DANGER: Failure to do this may require you to need to re-execute the script again to operate correctly.${NC}."
+    echo -n '(type yes to proceed): '
+    read VAULTVALID
+    if [[ "$VAULTVALID" == "yes" ]]; then
+      echo -e "${YELLOW} NOTE: We will perform DB Deployment Procedure. Please confirm all the details correctly before proceeding.${NC}"
+    else 
+      exit 1
+    fi
+}
+
 function execute-db-deploy-rds-tfapply {
     DB_DIRECTORY=$1
     echo -e "${RED}DANGER:${NC} ${YELLOW}PLEASE WAIT PATIENTLY UNTIL ALL PROCEDURE COMPLETED PROPERLY. IF THERE IS TROUBLE PLEASE CALL ASSISTANCE TO INFRA-TEAM IMMEDIATELY${NC}"
@@ -95,7 +110,8 @@ function execute-db-deploy-rds-tfapply {
 
 function execute-db-deploy-apsara-tfapply {
     DB_DIRECTORY=$1
-    ENVIRONMENT=$2
+    DB_NAME=$2
+    ENVIRONMENT=$3
     echo -e "${RED}DANGER:${NC} ${YELLOW}PLEASE WAIT PATIENTLY UNTIL ALL PROCEDURE COMPLETED PROPERLY. IF THERE IS TROUBLE PLEASE CALL ASSISTANCE TO INFRA-TEAM IMMEDIATELY${NC}"
     echo -e "${YELLOW}WILL INVOKE TERRAFORM APPLY. Please type exactly 'yes' if you are prompted by Terraform.${NC}" 
     sleep "5"
@@ -110,31 +126,34 @@ function execute-db-deploy-apsara-tfapply {
     popd
 
     if [ "$TFAPPLY" == "SUCCESS" ]; then
+      PUBLIC_CONNECTION=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.public_connection')
+      SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
+    
       pushd $DB_DIRECTORY
-          DB_HOST=$(cat apsara_db.json | $jq -r .apsara_db_host.value)
           DB_USER=$(cat apsara_db.json | $jq -r .apsara_db_user.value)
-          DB_PORT=$(cat apsara_db.json | $jq -r .apsara_db_port.value)
           DB_PASSWORD=$(cat PGPASSWORD)
       popd
 
       echo -e "${GREEN}[DBCTL]${NC} Waiting for Terraform changes successfully propagated (15 seconds sleep pause)"
       sleep 15
-
-      # echo -e "${GREEN}[DBCTL]${NC} Will bootstrap Apsara DB."
-      # echo "PGPASSWORD=$DB_PASSWORD psql -f sql/create-db.sql -h $DB_PUBLIC_HOST -p $DB_PORT -d postgres -U $DB_USER"
-      SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
-
+      
       if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
-        echo -e "${GREEN}[DBCTL]${NC} Will bootstrap Apsara DB Database via SSH tunnel"
+        pushd $DB_DIRECTORY
+            DB_HOST=$(cat apsara_db.json | $jq -r .apsara_db_host.value)
+            DB_USER=$(cat apsara_db.json | $jq -r .apsara_db_user.value)
+            DB_PORT=$(cat apsara_db.json | $jq -r .apsara_db_port.value)
+            DB_PASSWORD=$(cat PGPASSWORD)
+        popd
+      
+        DB_SSH_TUNNEL_IDENTIFIER="$DB_NAME.$ENVIRONMENT"
         DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_port')
         DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_host')
-
-        ./dbctl tunnel create ${DB_NAME} postgres ${ENVIRONMENT}
+        DB_TARGET_HOST=$DB_HOST
+        DB_TARGET_PORT=$DB_PORT
+        ./dbctl util ssh-tunnel $DB_SSH_TUNNEL_IDENTIFIER $DB_SSH_TUNNEL_HOST $DB_SSH_TUNNEL_PORT $DB_TARGET_HOST $DB_TARGET_PORT
         pushd $DB_DIRECTORY
             PGPASSWORD=$DB_PASSWORD psql -f sql/create-db.sql -h 127.0.0.1 -p ${DB_SSH_TUNNEL_PORT} -d postgres -U $DB_USER
         popd
-        ./dbctl tunnel destroy ${DB_NAME} postgres ${ENVIRONMENT}
-
         echo -e "db.apsara.deployed.tunnel.host: ${DB_SSH_TUNNEL_HOST}" > $DB_DIRECTORY/deployed_db_details.yml
         echo -e "db.apsara.deployed.tunnel.port: ${DB_SSH_TUNNEL_PORT}" > $DB_DIRECTORY/deployed_db_details.yml
         echo -e "db.apsara.deployed.db.host: ${DB_HOST}" >> $DB_DIRECTORY/deployed_db_details.yml
@@ -142,8 +161,79 @@ function execute-db-deploy-apsara-tfapply {
         $yq w -s $DB_DIRECTORY/deployed_db_details.yml $DB_DIRECTORY/${ENVIRONMENT}.yml > $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml
         rm -f $DB_DIRECTORY/deployed_db_details.yml
       else
-        echo -e "${GREEN}[DBCTL]${NC} Will bootstrap Apsara DB Database"
-        PGPASSWORD=$DB_PASSWORD psql -f sql/create-db.sql -h ${DB_HOST} -p ${DB_PORT} -d postgres -U ${DB_USER}
+        pushd $DB_DIRECTORY
+          if [[ "$PUBLIC_CONNECTION" == "true" ]]; then
+            DB_HOST=$(cat apsara_db.json | $jq -r .apsara_db_public_host.value)
+            DB_PORT=$(cat apsara_db.json | $jq -r .apsara_db_public_port.value)
+          fi
+          echo -e "${GREEN}[DBCTL]${NC} Will bootstrap Apsara DB Database"
+          PGPASSWORD=$DB_PASSWORD psql -f sql/create-db.sql -h ${DB_HOST} -p ${DB_PORT} -d postgres -U ${DB_USER}
+        popd
+      fi
+    fi
+}
+
+function execute-db-deploy-gcp-tfapply {
+    DB_DIRECTORY=$1
+    DB_NAME=$2
+    ENVIRONMENT=$3
+    echo -e "${RED}DANGER:${NC} ${YELLOW}PLEASE WAIT PATIENTLY UNTIL ALL PROCEDURE COMPLETED PROPERLY. IF THERE IS TROUBLE PLEASE CALL ASSISTANCE TO INFRA-TEAM IMMEDIATELY${NC}"
+    echo -e "${YELLOW}WILL INVOKE TERRAFORM APPLY. Please type exactly 'yes' if you are prompted by Terraform.${NC}" 
+    sleep "5"
+    mkdir -p $DB_DIRECTORY/.bin.db
+    cp ./.bin.db/terraform $DB_DIRECTORY/.bin.db/terraform
+    cp ./.bin.db/jq $DB_DIRECTORY/.bin.db/jq
+    cp ./.bin.db/yq $DB_DIRECTORY/.bin.db/yq
+
+    pushd $DB_DIRECTORY
+    ./tfapply
+    TFAPPLY=$(cat TFAPPLYOUTPUT)
+    popd
+
+    if [ "$TFAPPLY" == "SUCCESS" ]; then
+      PUBLIC_CONNECTION=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.public_connection.enabled')
+      SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.ssh_tunnel.enabled')
+    
+      pushd $DB_DIRECTORY
+          DB_USER=$(cat gcp_db.json | $jq -r .gcp_db_user.value)
+          DB_PASSWORD=$(cat PGPASSWORD)
+      popd
+
+      echo -e "${GREEN}[DBCTL]${NC} Waiting for Terraform changes successfully propagated (15 seconds sleep pause)"
+      sleep 15
+      
+      if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
+        pushd $DB_DIRECTORY
+            DB_HOST=$(cat gcp_db.json | $jq -r .gcp_db_private_ip.value)
+            DB_USER=$(cat gcp_db.json | $jq -r .gcp_db_user.value)
+            DB_PORT=$(cat gcp_db.json | $jq -r .gcp_db_private_port.value)
+            DB_PASSWORD=$(cat PGPASSWORD)
+        popd
+      
+        DB_SSH_TUNNEL_IDENTIFIER="$DB_NAME.$ENVIRONMENT"
+        DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.ssh_tunnel.tunnel_port')
+        DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.ssh_tunnel.tunnel_host')
+        DB_TARGET_HOST=$DB_HOST
+        DB_TARGET_PORT=$DB_PORT
+        ./dbctl util ssh-tunnel $DB_SSH_TUNNEL_IDENTIFIER $DB_SSH_TUNNEL_HOST $DB_SSH_TUNNEL_PORT $DB_TARGET_HOST $DB_TARGET_PORT
+        pushd $DB_DIRECTORY
+            PGPASSWORD=$DB_PASSWORD psql -f sql/create-db.sql -h 127.0.0.1 -p ${DB_SSH_TUNNEL_PORT} -d postgres -U $DB_USER
+        popd
+        echo -e "db.gcp.deployed.tunnel.host: ${DB_SSH_TUNNEL_HOST}" > $DB_DIRECTORY/deployed_db_details.yml
+        echo -e "db.gcp.deployed.tunnel.port: ${DB_SSH_TUNNEL_PORT}" > $DB_DIRECTORY/deployed_db_details.yml
+        echo -e "db.gcp.deployed.db.host: ${DB_HOST}" >> $DB_DIRECTORY/deployed_db_details.yml
+        echo -e "db.gcp.deployed.db.port: ${DB_PORT}" >> $DB_DIRECTORY/deployed_db_details.yml
+        $yq w -s $DB_DIRECTORY/deployed_db_details.yml $DB_DIRECTORY/${ENVIRONMENT}.yml > $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml
+        rm -f $DB_DIRECTORY/deployed_db_details.yml
+      else
+        pushd $DB_DIRECTORY
+          if [[ "$PUBLIC_CONNECTION" == "true" ]]; then
+            DB_HOST=$(cat gcp_db.json | $jq -r .gcp_db_public_ip.value)
+            DB_PORT=$(cat gcp_db.json | $jq -r .gcp_db_public_port.value)
+          fi
+          echo -e "${GREEN}[DBCTL]${NC} Will bootstrap GCP DB Database"
+          PGPASSWORD=$DB_PASSWORD psql -f sql/create-db.sql -h ${DB_HOST} -p ${DB_PORT} -d postgres -U ${DB_USER}
+        popd
       fi
     fi
 }
@@ -160,7 +250,7 @@ function db-deploy-validate {
     fi
 
     DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
-    if [[ "$DB_DEPLOYMENT_TYPE" != "hosted" && "$DB_DEPLOYMENT_TYPE" != "rds" && $DB_DEPLOYMENT_TYPE != "apsara" ]]; then
+    if [[ "$DB_DEPLOYMENT_TYPE" != "hosted" && "$DB_DEPLOYMENT_TYPE" != "rds" && $DB_DEPLOYMENT_TYPE != "apsara" && "$DB_DEPLOYMENT_TYPE" != "gcp"  ]]; then
         echo -e "${RED}ERROR:${NC} Deployment type is not supported for ${YELLOW}${DB_NAME}/${ENVIRONMENT}.yml${NC}. [Deployment-Type: ${YELLOW}${DEPLOYMENT_TYPE}${NC} - supported: ${YELLOW}hosted, rds${NC}]"
         exit 1
     fi
@@ -188,6 +278,13 @@ function db-deploy-validate {
       fi
       if [[ -z "$ALICLOUD_SECRET_ACCESS_KEY" ]]; then
         echo -e "${RED}[ERROR]${NC} No ALICLOUD_SECRET_ACCESS_KEY specified. Please export it to your environment variable."
+        exit 1
+      fi
+    fi
+
+    if [[ "$DB_DEPLOYMENT_TYPE" == "gcp" ]]; then
+      if [[ -z "$GOOGLE_CREDENTIALS_FILE" ]]; then
+        echo -e "${RED}[ERROR]${NC} No GOOGLE_CREDENTIALS_FILE specified. Please export it to your environment variable."
         exit 1
       fi
     fi
@@ -264,6 +361,9 @@ function db-deploy-execute {
     if [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
       DB_PROVIDER_INSTANCE_ID=$($yq r $BLUEPRINT_DATABASE_FILE db.apsara.db_provider_instance.id)
       DB_PROVIDER_INSTANCE_HOST=$($yq r $BLUEPRINT_DATABASE_FILE db.apsara.db_provider_instance.host)
+    elif [[ "$DB_DEPLOYMENT_TYPE" == "gcp" ]]; then
+      DB_PROVIDER_INSTANCE_ID=$($yq r $BLUEPRINT_DATABASE_FILE db.gcp.db_provider_instance.name)
+      DB_PROVIDER_INSTANCE_HOST="-"
     fi
 
     if [[ "$DB_PROVIDER_INSTANCE_ID" != "" ]] && [[ "$DB_PROVIDER_INSTANCE_ID" != "null" ]] && [[ "$DB_PROVIDER_INSTANCE_HOST" != "" ]] && [[ "$DB_PROVIDER_INSTANCE_HOST" != "null" ]]; then
@@ -289,7 +389,24 @@ function db-deploy-execute {
       
       if [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
         execute-db-deploy-apsara-confirmation $DB_DIRECTORY
-        execute-db-deploy-apsara-tfapply $DB_DIRECTORY $ENVIRONMENT
+        execute-db-deploy-apsara-tfapply $DB_DIRECTORY $DB_NAME $ENVIRONMENT
+        TFAPPLY=$(cat $DB_DIRECTORY/TFAPPLYOUTPUT)
+        if [ "$TFAPPLY" == "SUCCESS" ]; then
+          configure-secrets-to-vault $DB_DIRECTORY
+          VAULTUPLOAD=$(cat $DB_DIRECTORY/VAULTUPLOADOUTPUT)
+          if [ "$VAULTUPLOAD" == "SUCCESS" ]; then
+            echo -e "${GREEN} [SUCCESS] ${NC} Successfully synchronize DB Credential to Secrets Management - Vault"
+          else
+            echo -e "${RED}ERROR: Upload DB Credentials to Vault IS NOT COMPLETED properly. Please do re-deploy.${NC}"
+            exit 1
+          fi
+        else
+          echo -e "${RED}ERROR: TERRAFORM APPLY IS NOT INVOKED. DB Deploy procedure will not continue. Please do re-deploy.${NC}"
+          exit 1
+        fi
+      elif [[ "$DB_DEPLOYMENT_TYPE" == "gcp" ]]; then
+        execute-db-deploy-gcp-confirmation $DB_DIRECTORY
+        execute-db-deploy-gcp-tfapply $DB_DIRECTORY $DB_NAME $ENVIRONMENT
         TFAPPLY=$(cat $DB_DIRECTORY/TFAPPLYOUTPUT)
         if [ "$TFAPPLY" == "SUCCESS" ]; then
           configure-secrets-to-vault $DB_DIRECTORY
@@ -351,7 +468,7 @@ function db-deploy-execute {
         fi
       elif [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
         execute-db-deploy-apsara-confirmation $DB_DIRECTORY
-        execute-db-deploy-apsara-tfapply $DB_DIRECTORY $ENVIRONMENT
+        execute-db-deploy-apsara-tfapply $DB_DIRECTORY $DB_NAME $ENVIRONMENT
         TFAPPLY=$(cat $DB_DIRECTORY/TFAPPLYOUTPUT)
         if [ "$TFAPPLY" == "SUCCESS" ]; then
           configure-secrets-to-vault $DB_DIRECTORY
@@ -375,6 +492,23 @@ function db-deploy-execute {
           echo -e "${RED}ERROR: Upload DB Credentials to Vault IS NOT COMPLETED properly. Please do re-deploy.${NC}"
           exit 1
         fi
+      elif [[ "$DB_DEPLOYMENT_TYPE" == "gcp" ]]; then
+        execute-db-deploy-gcp-confirmation $DB_DIRECTORY
+        execute-db-deploy-gcp-tfapply $DB_DIRECTORY $DB_NAME $ENVIRONMENT
+        TFAPPLY=$(cat $DB_DIRECTORY/TFAPPLYOUTPUT)
+        if [ "$TFAPPLY" == "SUCCESS" ]; then
+          configure-secrets-to-vault $DB_DIRECTORY
+          VAULTUPLOAD=$(cat $DB_DIRECTORY/VAULTUPLOADOUTPUT)
+          if [ "$VAULTUPLOAD" == "SUCCESS" ]; then
+            echo -e "${GREEN} [SUCCESS] ${NC} Successfully synchronize DB Credential to Secrets Management - Vault"
+          else
+            echo -e "${RED}ERROR: Upload DB Credentials to Vault IS NOT COMPLETED properly. Please do re-deploy.${NC}"
+            exit 1
+          fi
+        else
+          echo -e "${RED}ERROR: TERRAFORM APPLY IS NOT INVOKED. DB Deploy procedure will not continue. Please do re-deploy.${NC}"
+          exit 1
+        fi
       fi
     fi
 }
@@ -389,6 +523,8 @@ else
     if [[ -z "$1" ]] || [[ -z "$2" ]]; then
         exit 3
     else
+        source ./db/app/meta
+        source ./db/app/namespace
         db-deploy-validate $1 $2
         db-deploy-execute $1 $2
     fi
diff --git a/cli/db/app/postgres/psql b/cli/db/app/postgres/psql
--- a/cli/db/app/postgres/psql
+++ b/cli/db/app/postgres/psql
@@ -2,9 +2,6 @@
 set -e
 trap "exit" INT
 
-source ./db/app/meta
-source ./db/app/namespace
-
 yq=./.bin.db/yq
 CURRENT_DIRECTORY=$(pwd)
 
@@ -17,17 +14,18 @@ function db-psql-validate {
   local BLUEPRINT_DATABASE_FILE=${BLUEPRINT_DIRECTORY}/postgres/${DB_NAME}/${ENVIRONMENT}.yml
   local BLUEPRINT_ROLES_DIRECTORY=${BLUEPRINT_DIRECTORY}/postgres/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}
   local BLUEPRINT_ROLES_CREATION_FILE=${BLUEPRINT_DIRECTORY}/postgres/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/creation.sql
-  
+
   if [[ ! -f "${BLUEPRINT_DATABASE_FILE}" ]]; then
       echo -e "${RED}ERROR:${NC} No database specification file found for ${YELLOW}${DB_NAME}/${ENVIRONMENT}.yml${NC}. [${YELLOW}${BLUEPRINT_DATABASE_FILE}${NC}]"
       exit 1
   fi
 
   DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
-  if [[ "$DB_DEPLOYMENT_TYPE" != "hosted" && "$DB_DEPLOYMENT_TYPE" != "rds" && "$DB_DEPLOYMENT_TYPE" != "apsara" ]]; then
+  if [[ "$DB_DEPLOYMENT_TYPE" != "hosted" && "$DB_DEPLOYMENT_TYPE" != "rds" && $DB_DEPLOYMENT_TYPE != "apsara" && "$DB_DEPLOYMENT_TYPE" != "gcp"  ]]; then
       echo -e "${RED}ERROR:${NC} Deployment type is not supported for ${YELLOW}${DB_NAME}/${ENVIRONMENT}.yml${NC}. [Deployment-Type: ${YELLOW}${DEPLOYMENT_TYPE}${NC} - supported: ${YELLOW}hosted, rds${NC}]"
       exit 1
   fi
+
 
   if [[ -z "$GITHUB_USERNAME" ]]; then
     echo -e "${RED}[ERROR]${NC} No GITHUB_USERNAME specified. Please export it to your environment variable."
@@ -37,7 +35,7 @@ function db-psql-validate {
   if [[ ! -d "${BLUEPRINT_ROLES_DIRECTORY}" ]]; then
     echo -e "${RED}ERROR:${NC} No ROLES specification directory found for ${YELLOW}${DB_NAME}/${ENVIRONMENT}/${ROLE_NAME}${NC}. [${YELLOW}${BLUEPRINT_ROLES_DIRECTORY}${NC}]"
     exit 1
-  fi  
+  fi
 
   if [[ ! -f "${BLUEPRINT_ROLES_CREATION_FILE}" ]]; then
     echo -e "${RED}ERROR:${NC} No ROLES creation.sql file found for ${YELLOW}${DB_NAME}/${ENVIRONMENT}/${ROLE_NAME}${NC}. [${YELLOW}${BLUEPRINT_ROLES_CREATION_FILE}${NC}]"
@@ -49,36 +47,96 @@ function db-psql-execute {
   local DB_NAME=$1
   local ENVIRONMENT=$2
   local ROLE_NAME=$3
-  
+
   local BLUEPRINT_DIRECTORY=$(pwd)/db/blueprint
   local BLUEPRINT_DATABASE_FILE=${BLUEPRINT_DIRECTORY}/postgres/${DB_NAME}/${ENVIRONMENT}.yml
   local BLUEPRINT_ROLES_DIRECTORY=${BLUEPRINT_DIRECTORY}/postgres/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}
   local BLUEPRINT_ROLES_CREATION_FILE=${BLUEPRINT_DIRECTORY}/postgres/${DB_NAME}/__roles__/${ENVIRONMENT}/${ROLE_NAME}/creation.sql
-  
-  DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
-  DB_HOST=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_host")
+
   export IDENTIFIER=${DB_DEPLOYMENT_TYPE}.postgres.${ORGANIZATION}.${TEAM}.${PRODUCT}.${DB_NAME}.${ENVIRONMENT}
   export DB_DIRECTORY=$CURRENT_DIRECTORY/.run.db/${IDENTIFIER}
   mkdir -p ${DB_DIRECTORY}
   ./dbctl postgres role get-credential $DB_NAME $ENVIRONMENT $ROLE_NAME
   $(./dbctl postgres role use-credential $DB_NAME $ENVIRONMENT $ROLE_NAME)
+  echo -e "${YELLOW}==========================================================================================${NC}"
+  echo -e "${GREEN}[DBCTL]${NC} PSQL Client for - ${YELLOW}${DB_HOST}/${DB_NAME}/${ROLE_NAME}${NC} - "
+  echo -e "${YELLOW}==========================================================================================${NC}"
 
-  local SSH_ENABLED=$($yq r $BLUEPRINT_DATABASE_FILE "db.${DB_DEPLOYMENT_TYPE}.db_provider_option.ssh_tunnel.enabled")
-  if [[ ${SSH_ENABLED} == "true" ]]; then
-    local SSH_PORT=$($yq r $BLUEPRINT_DATABASE_FILE "db.${DB_DEPLOYMENT_TYPE}.db_provider_option.ssh_tunnel.tunnel_port")
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    echo -e "${GREEN}[DBCTL]${NC} PSQL Client for - ${YELLOW}127.0.0.1:${SSH_PORT}/${DB_NAME}/${ROLE_NAME}${NC} - "
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    ./dbctl tunnel create ${DB_NAME} postgres ${ENVIRONMENT}
-    PGPASSWORD=$DBCTL_PASSWORD psql -U $DBCTL_USERNAME -d $DB_NAME --host=127.0.0.1 --port=${SSH_PORT}
-    ./dbctl tunnel destroy ${DB_NAME} postgres ${ENVIRONMENT}
-  else
-    # TODO
-    # this currently only works on hosted as DB_HOST value will be null if it's not hosted
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    echo -e "${GREEN}[DBCTL]${NC} PSQL Client for - ${YELLOW}${DB_HOST}/${DB_NAME}/${ROLE_NAME}${NC} - "
-    echo -e "${YELLOW}==========================================================================================${NC}"
-    PGPASSWORD=$DBCTL_PASSWORD psql -U $DBCTL_USERNAME -d $DB_NAME -h $DB_HOST
+  DB_DEPLOYMENT_TYPE=$($yq r $BLUEPRINT_DATABASE_FILE 'db.deployment')
+
+  if [[ "$DB_DEPLOYMENT_TYPE" == "hosted" ]]; then
+    DB_HOST=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_host")
+    DB_PORT=$($yq r $BLUEPRINT_DATABASE_FILE "db.$DB_DEPLOYMENT_TYPE.db_port")
+    if [[ "$DB_PORT" == "null" ]]; then
+      DB_PORT=5432
+    fi
+    PGPASSWORD=${DBCTL_PASSWORD} psql -U ${DBCTL_USERNAME} -d ${DB_NAME} -h ${DB_HOST} -p ${DB_PORT}
+  elif [[ "$DB_DEPLOYMENT_TYPE" == "apsara" ]]; then
+    SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.enabled')
+
+    if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
+      DB_SSH_TUNNEL_IDENTIFIER="$DB_NAME.$ENVIRONMENT"
+      DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_port')
+      DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_option.ssh_tunnel.tunnel_host')
+      DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.host')
+      DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.port')
+      if [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+          DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.host')
+          DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.port')
+          if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+            echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+            exit 1;
+          fi
+      fi
+      ./dbctl util ssh-tunnel $DB_SSH_TUNNEL_IDENTIFIER $DB_SSH_TUNNEL_HOST $DB_SSH_TUNNEL_PORT $DB_TARGET_HOST $DB_TARGET_PORT
+
+      PGPASSWORD=${DBCTL_PASSWORD} psql -U ${DBCTL_USERNAME} -d ${DB_NAME} -h localhost -p ${DB_SSH_TUNNEL_PORT}
+    else
+      DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.host')
+      DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.apsara.db_provider_instance.port')
+      if [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+          DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.host')
+          DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.apsara.deployed.db.port')
+          if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+            echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+            exit 1;
+          fi
+      fi
+      PGPASSWORD=${DBCTL_PASSWORD} psql -U ${DBCTL_USERNAME} -d ${DB_NAME} -h ${DB_TARGET_HOST} -p ${DB_TARGET_PORT}
+    fi
+  elif [[ "$DB_DEPLOYMENT_TYPE" == "gcp" ]]; then
+    SSH_TUNNEL_ENABLED=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.ssh_tunnel.enabled')
+
+    if [[ "$SSH_TUNNEL_ENABLED" == "true" ]]; then
+      DB_SSH_TUNNEL_IDENTIFIER="$DB_NAME.$ENVIRONMENT"
+      DB_SSH_TUNNEL_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.ssh_tunnel.tunnel_port')
+      DB_SSH_TUNNEL_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_option.ssh_tunnel.tunnel_host')
+      DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_instance.host')
+      DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_instance.port')
+      if [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+          DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.gcp.deployed.db.host')
+          DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.gcp.deployed.db.port')
+          if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+            echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+            exit 1;
+          fi
+      fi
+      ./dbctl util ssh-tunnel $DB_SSH_TUNNEL_IDENTIFIER $DB_SSH_TUNNEL_HOST $DB_SSH_TUNNEL_PORT $DB_TARGET_HOST $DB_TARGET_PORT
+
+      PGPASSWORD=${DBCTL_PASSWORD} psql -U ${DBCTL_USERNAME} -d ${DB_NAME} -h localhost -p ${DB_SSH_TUNNEL_PORT}
+    else
+      DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_instance.host')
+      DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}.yml 'db.gcp.db_provider_instance.port')
+      if [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+          DB_TARGET_HOST=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.gcp.deployed.db.host')
+          DB_TARGET_PORT=$($yq r $DB_DIRECTORY/${ENVIRONMENT}-deployed.yml 'db.gcp.deployed.db.port')
+          if [[ "$DB_TARGET_HOST" == "" ]] || [[ "$DB_TARGET_HOST" == "null" ]] || [[ "$DB_TARGET_PORT" == "" ]] || [[ "$DB_TARGET_PORT" == "null" ]]; then
+            echo -e "${RED}ERROR:${NC} Invalid ${ENVIRONMENT}-deployed.yml found in ${YELLOW}${DB_DIRECTORY}.${NC} Please re-run ${YELLOW}./dbctl postgres deploy $DB_NAME $ENVIRONMENT${NC} first."
+            exit 1;
+          fi
+      fi
+      PGPASSWORD=${DBCTL_PASSWORD} psql -U ${DBCTL_USERNAME} -d ${DB_NAME} -h ${DB_TARGET_HOST} -p ${DB_TARGET_PORT}
+    fi
   fi
 }
 
@@ -92,6 +150,8 @@ else
     if [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -z "$3" ]]; then
         exit 3
     else
+        source ./db/app/meta
+        source ./db/app/namespace
         db-psql-validate $1 $2 $3
         db-psql-execute $1 $2 $3
     fi
